version: '2'
services:
  identidock:
    build: .
    ports:
      - "9090:9090"
      - "9191:9191"
    environment:
      ENV: 
    volumes:
      - ./app:/app
  dnmonster:
    image: amouat/dnmonster
  redis:
    image: redis
